#!/bin/bash
# utility script to parse hex html generated by artem
# ./gen-sammy-function.sh ../static/sammy1.html sammy1  > ../autoload/sammy1.vim
# ./gen-sammy-function.sh ../static/sammy2.html sammy2  > ../autoload/sammy2.vim
# ./gen-sammy-function.sh ../static/sammy3.html sammy3  > ../autoload/sammy3.vim

temp_file="$(mktemp)"
input="$1"
prefix=${2:-sammy1}
func_start="function! $prefix#Highlight()\n"

awk '{while (match($0, /#.{6}/)) {print substr($0, RSTART, RLENGTH);$0=substr($0, RSTART+RLENGTH)}}' $input | \
    awk ' { for (c = 1; c <= NF; c++)printf("%s %s", $c, (NR % 125 == 0) ? "\n" : "") }' | \
    awk ' { for (c = 1; c <= NF; c++) { printf("  highlight %s_%s_%s guibg=%s\n", "sammy", NR, c, $c) }; } ' | \
    shuf | \
    awk -v func_start="$func_start" ' BEGIN{ printf("%s", func_start ) } { { printf("%s\n%s", $0, ($1 == "highlight" && NR % 3000 == 0) ? "  redraw\n" : "" ) } } ' > "$temp_file"

grep -v '.*matchaddpos.*' "$temp_file"
printf "endfunction\n\n"
rm "$temp_file"

